package com.widhin.jetmovie.model

import com.widhin.jetmovie.R

object FakeMovieDataSource {
    val dummyMovie = listOf(
        Movie(1, R.drawable.movie_1, "Shingeki no Kyojin", "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.", 1000000),
        Movie(2, R.drawable.movie_2, "SPY x FAMILY", "Master spy Twilight is the best at what he does when it comes to going undercover on dangerous missions in the name of a better world. But when he receives the ultimate impossible assignment—get married and have a kid—he may finally be in over his head! Not one to depend on others, Twilight has his work cut out for him procuring both a wife and a child for his mission to infiltrate an elite private school. What he doesn’t know is that the wife he’s chosen is an assassin and the child he’s adopted is a telepath!", 75000),
        Movie(3, R.drawable.movie_3, "Castaway Diva", "Fifteen years after being stranded on a remote island, an aspiring singer reenters society — stopping at nothing to pursue her dream of becoming a diva.", 65000),
        Movie(4, R.drawable.movie_4, "The Marvels", "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.", 45000),
        Movie(5, R.drawable.movie_5, "Jujutsu Kaisen", "Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses… and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.", 500000),
        Movie(6, R.drawable.movie_6, "Vigilante", "Metropolitan Investigation Team Unit tracking an organization called Vigilante, which judges the wicked people who escaped the law which has become a social phenomenon.", 55000),
        Movie(7, R.drawable.movie_7, "Loki", "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.", 60000),
        Movie(8, R.drawable.movie_8, "Oppenheimer", "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.", 60000),
        Movie(9, R.drawable.movie_9, "Boys Over Flowers", "Unassuming high school girl Jan-di stands up to — and eventually falls for — a spoiled rich kid who belongs to the school’s most powerful clique.", 40000),
        Movie(10, R.drawable.movie_10, "The Creator", "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.", 25000)
    )
}